CM2301/CM2301/urls.py
from django.conf.urls import patterns, include, url
from django.http import HttpResponse

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'CM2301.views.home', name='home'),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    
    url(r'^', include('learn.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

CM2301/learn/urls.py
from django.conf.urls import patterns, include, url
from learn.views.faq import *
from learn.views. announcement import *
from learn.views.module import *
from learn.views.announcement import *
from learn.views.management import *
from learn.views.coursework import *
from django.conf.urls.static import static



uuid = '[a-f0-9]{8}[a-f0-9]{4}[a-f0-9]{4}[a-f0-9]{4}[a-f0-9]{12}'

urlpatterns = patterns('',
    # /
    url(r'^$', 'learn.views.misc.home', name='home'),
    #url(r'^videos/$', 'learn.views.videos'),
    url(r'^videos/submit/$', 'learn.views.video.submit'),
    url(r'^login/$', 'learn.views.misc.custom_login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/login'}),

    #management stuff
    url(r'^management/$', 'learn.views.management.overview'),

    url(r'^management/users$', login_required(UserListView.as_view())),
    url(r'^management/users/create$', login_required(UserCreateView.as_view())),
    url(r'^management/users/(?P<pk>%s)/update' % (uuid), login_required(UserUpdateView.as_view())),

    url(r'^management/courses$', login_required(CourseListView.as_view())),
    url(r'^management/courses/create$', login_required(CourseCreateView.as_view())),
    url(r'^management/courses/(?P<pk>%s)/details$' % (uuid), login_required(CourseDetailView.as_view())),
    url(r'^management/courses/(?P<pk>%s)/update$' % (uuid), login_required(CourseUpdateView.as_view())),
    url(r'^management/courses/(?P<course_id>%s)/details/unassociate/(?P<module_id>%s)$' % (uuid, uuid), 'learn.views.management.unassociate_module'),
    url(r'^management/courses/(?P<course_id>%s)/details/associate$' % (uuid), 'learn.views.management.associate_module'),


    url(r'^management/modules$', login_required(ModuleListView.as_view())),
    url(r'^management/modules/(?P<pk>%s)/delete$' % (uuid), login_required(ModuleDeleteView.as_view())),
    url(r'^management/modules/(?P<pk>%s)/lectures' % (uuid), login_required(LectureListView.as_view())),

    url(r'management/modules/(?P<pk>%s)/coursework/$' % (uuid), login_required(ManagementCourseworkTaskListView.as_view())),
    url(r'management/modules/(?P<module>%s)/coursework/(?P<pk>%s)$' % (uuid, uuid), login_required(ManagementCourseworkSubmissionListView.as_view())),
    url(r'management/modules/(?P<module_id>%s)/coursework/(?P<task_id>%s)/mark/(?P<submission_id>%s)$' % (uuid, uuid, uuid), 'learn.views.management.mark_coursework'),


    #Announcement Stuff
    url(r'^announcement/create/$', login_required(CreateAnnouncementView.as_view())),


    #Course listing
    url(r'^courses/(?P<course_id>%s)$' % (uuid), 'learn.views.course.course'),
    
    #Video URL's
    url(r'^videos/$', 'learn.views.video.all'),
    url(r'^videos/(?P<video_id>%s)/$' % (uuid), 'learn.views.video.video'),
    url(r'^videos/(?P<video_id>%s)/serve/(.+)$' % (uuid), 'learn.views.video.serve'),
    url(r'^videos/formats/(?P<video_format_id>%s)/serve/(.+)$' % (uuid), 'learn.views.video.format_serve'),
    url(r'^videos/create/$', 'learn.views.video.create'),
    url(r'^videos/(?P<video_id>%s)/progress/$' % (uuid), 'learn.views.video.conversion_progress'),
    url(r'^thumbnails/(?P<thumbnail_id>%s)/$' % (uuid), 'learn.views.video.thumbnail'),
        

    #Test URL'sq
    url(r'^tests/(?P<test_id>%s)/$'% (uuid), 'learn.views.test.test'),
    

    #Module URL's
    url(r'^modules/$', 'learn.views.module.modules'),
    url(r'^modules/create/$', CreateModuleView.as_view()),
    url(r'^modules/(?P<module_id>%s)/$' % (uuid), 'learn.views.module.module'),
    url(r'^modules/(?P<module_id>%s)/lectures/$' % (uuid), 'learn.views.module.lectures'),
    url(r'^modules/(?P<module_id>%s)/attachments/$' % (uuid), 'learn.views.module.attachments'),
    url(r'^modules/(?P<module_id>%s)/tests/$' % (uuid), 'learn.views.module.tests'),
    url(r'^modules/(?P<module_id>%s)/faqs/$' % (uuid), 'learn.views.faq.faqs'),
    url(r'^modules/(?P<module_id>%s)/faqs/ask/$' % (uuid), login_required(CreateFAQQuestionView.as_view())),
    url(r'^modules/(?P<module_id>%s)/faqs/(?P<faq_id>%s)/answer/$' % (uuid, uuid), login_required(CreateFAQAnswerView.as_view())),

    url(r'^modules/(?P<pk>%s)/coursework$' % (uuid), login_required(CourseworkListView.as_view())),
    url(r'^modules/(?P<pk>%s)/coursework/create$' % (uuid), login_required(CourseworkTaskCreateView.as_view())),
    url(r'^modules/(?P<pk>%s)/create$' % (uuid), login_required(CourseworkListView.as_view())),
    url(r'^modules/(?P<module_id>%s)/coursework/(?P<coursework_id>%s)/submit$' % (uuid, uuid), 'learn.views.coursework.coursework_submission'),

    #Lecture URL's
    url(r'^modules/(?P<module_id>%s)/lectures/create/$' % (uuid), 'learn.views.lecture.create'),
    
    url(r'^lectures/create/$', 'learn.views.lecture.create'),
    url(r'^lectures/(?P<lecture_id>%s)/$' % (uuid), 'learn.views.lecture.view'),    
    
    #Attachment URL's
    url(r'^attachments/(?P<attachment_id>%s)/$' % (uuid), 'learn.views.attachment.attachment'),
    url(r'^attachments/(?P<attachment_id>%s)/download/$' % (uuid), 'learn.views.attachment.download_all_revisions'),
    url(r'^attachments/(?P<attachment_id>%s)/add/$' % (uuid), 'learn.views.attachment.revision_add'),
    url(r'^revisions/(?P<revision_id>%s)/$' % (uuid), 'learn.views.attachment.revision'),
    url(r'^revisions/(?P<revision_id>%s)/delete$' % (uuid), 'learn.views.attachment.revision_delete'),
    url(r'^revisions/(?P<revision_id>%s)/download/$' % (uuid), 'learn.views.attachment.revision_download'),
    url(r'^(.*)/(?P<object_id>%s)/attachments/download/$' % (uuid), 'learn.views.attachment.download_all_attachments'),
    url(r'^(.*)/(?P<object_id>%s)/attachments/create/$' % (uuid), 'learn.views.attachment.attachment_create'),
    
    #Test URL's
    url(r'^tests/(?P<test_id>%s)/$' % (uuid), 'learn.views.test.test'),
    url(r'^tests/$', 'learn.views.test.tests'),
    url(r'^results/(?P<test_instance_id>%s)/$' % (uuid), 'learn.views.test.test_results'),
    
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CM2301/Learn/models/models.py
from django.db import models
import uuid

class Base(models.Model):
    """
    Base class containing common properties and methods for models.
    
    All models will extend this class.
    """
    
    """UUID of the object, as String"""
    uuid = models.CharField(max_length=36, primary_key=True)
    
    class Meta:
        app_label = "Learn"
        abstract = True
    
    def save(self, *args, **kwargs):
        """
        Overrides the django.model.save() method to add a random UUID
        to new objects before they are persisted to the DB.
        """
        if not self.uuid:
            uuid = str(uuid.uuid4())
        super(Base, self).save(*args, **kwargs)
        
    def get_data_fields(self):
        """
        Returns any DataFields that are related to the object.
        @return DataField Returns any DataField objects associated with the object
        """
        return
        
    
        
        
################################################################
#Core System
################################################################
        
class User(Base):
    """
    Represents a user of the system. 
    
    A User contains attributes that are common for any user of the system.
    Other attributes can be linked with a user using the UserField class
    """
    ##Forename of the User
    forename = models.CharField(max_length=50)
    ##Surname of the User
    surname = models.CharField(max_length=50)
    ##Username or alias for the User object
    username = models.CharField(max_length=25)
    ##Email address registered with the User
    email = models.EmailField(max_length=75)
    ##Phone number for the User
    phone = models.CharField(max_length=20)
    
    def add_user_field(self, UserField):
        """
        Adds a UserField object to the User
        
        @param UserField The UserField object to set as belonging to the user.
        @return UserField Returns the UserField added. 
        @throws UserDataException
        """
        return
    
class DataField(Base):
    """
    A UserField is a value attached to another object.
    
    Objects can have multiple DataFields allowing for an extensiable Schema
    """
    ##The object uuid the datafield belongs to
    object_uuid = models.CharField(max_length=36)
    ##The field key
    key = models.CharField(max_length=250)
    ##The field value
    value = models.TextField()
    
################################################################
#File Handling
################################################################

class Attachment(Base):
    """
    An Attachment is a collection of revisions. 
    
    Attachment objects can be used to derive a full file revision history, 
    and retrieve the original version of the file
    """
    
    ##The title of the Attachment
    title = models.CharField(max_length=50)
    ##The file name e.g file.pdf
    file_name = models.CharField(max_length=50)
    ##The description of the Attachment
    description = models.CharField(max_length=250)
    ##The User owning the Attachment, usually the uploader.
    owner = models.ForeignKey(User)
    
    def get_total_size(self):
        """
        Returns the total size used of all revisions in the Attachment object.
        
        @return: Float A float of the total size in Kb
        """
        return
    
    def remove_revision(self, revision_uuid):
        """
        Removes the revision from the attachment with the 
        specified uuid.
        
        @param UUID The uuid of the revision to be purged.
        @return Revision The Revision object removed.
        """
        return
    
    def purge_revisions(self):
        """
        Purges all Revisions but the most recent in the Attachment object.
        """
        return
    
    def get_all_revisions(self):
        """
        Returns an ordered List of revisions for the Attachment based on time uploaded.
        
        @return List Returns a list of all Revisions sorted descending order.
        """
        
    def add_revision(self, revision):
        """
        Adds the supplied Revision object to the Attachment with current timestamp.
        
        @param Revision The Revision object to add to the Attachment
        @throws AttachmentException If Revision file type is invalid.
        """
        
class Revision(Base):
    """
    A revision object represents a single file that belongs to an Attachment.
    
    This class facilitates Attachment versioning
    """
    ##The timestamp the document was uploaded/attached to the revision
    time_uploaded = models.DateTimeField(auto_now_add=True)
    ##The Attachment object the Revision belongs to.
    attachment = models.ForeignKey(Attachment)
    ###The File Object
    file = models.FileField(upload_to='/')
    ##Whether or not the Revision has been approved
    approved = models.BooleanField()
    ##The User whom owns the Revision - Usually the uploader.
    uploaded_by = models.ForeignKey(User)
    ##The file size of the Revision file.
    file_size = models.FloatField()
    
    def get_file(self):
        """
        Returns the File object for the current Revision.
        @return File Returns the File handler for the Revision
        """
        return
    
################################################################
#Lecturing Classes
################################################################
    
class Link(Base):
    """
    Holds to a resource.
    
    Links can be added to many other Objects.
    """
    ##The title for the Link story
    title = models.CharField(max_length=250)
    ##The description of the Link
    description = models.TextField()
    ##The Link URl in string form
    link = models.URLField(max_length=250)

class Video(Base):
    """
    Represents a video, can contain multiple VideoFormats.
    
    Contains video title, keywords and description.
    """
    ##The title of the Video
    title = models.CharField(max_length=50)
    ##The description for the video
    description = models.TextField()
    
    def get_file_paths(self):
        """
        Returns a dictionary of filepaths for every availiable format
        
        @return Dict Returns a dictionary of format:filepath
        """
        return
    
    def get_file_path(self, format):
        """
        Returns the video file path for the specified format
        
        @return String A string of the Format filepath
        """
        return
    
class VideoFormat(Revision):
    """
    Represents a specific video format containing a file.
    
    Belongs to a video object.
    """
    ##The container format as a string. e.g .ogg
    format = models.CharField(max_length=20)
    ##The encoding used for the video. e.g H.264
    encoding = models.CharField(max_length=50)
    ##The bitrate of the video
    bitrate = models.CharField(max_length=10)
    ##The Video object the format belongs to.
    video = models.ForeignKey(Video)
    
    def probe(self):
        """
        Return ffprobe class from video.
        
        Gets details about the video file using FFPROBE
        
        @return: ffprobe 
        """
        return
    
class Lecture(Base):
    """
    Represents a lecture in the system.
    
    Contains details about an individual lecture & references to
    lecture content (Videos, Attachments and Lecture Notes).
    """
    ##The title of the lecture
    title = models.CharField(max_length=50)
    ##The videos used in the lecture
    videos = models.ManyToManyField(Video)
    ##Attachments to be presented with the lecture
    attachments = models.ManyToManyField(Attachment)
    ##The date the Lecture becomes valid.
    validFrom = models.DateField()
    ##The date the lecture expires.
    validTo = models.DateField()
    ##Whether the lecture is visible
    visible = models.BooleanField(default=True)
    ##Links that may be useful.
    links = models.ManyToManyField(Link)
    ##Lecturers who teach the lecture. - They should be in the module lecturers.
    lecturers = models.ManyToManyField(User)
    
class Module(Base):
    """
    A module is a set of lectures belonging to multiple courses.
    
    Modules can share Lecture objects, Module objects can belong
    to multiple Course objects.
    """
    ##The title of the Module. E.g Python
    title = models.CharField(max_length=100)
    ##The module code - CM2103
    module_code = models.CharField(max_length=100)
    ##Attachments linked to the module obejct
    attachments = models.ManyToManyField(Attachment)
    ##The lectures used in the module
    lectures = models.ManyToManyField(Lecture)

class Course(Base):
    """
    A course represents a top level definition of a degree. 
    
    Contains a collection of modules
    """
    ##The title of the course
    title = models.CharField(max_length=50)
    ##The course code it holds e.g G400
    code = models.CharField(max_length=50)
    ##The description of the course
    description = models.TextField()
    ##The modules which are in the course
    modules = models.ManyToManyField(Module)
    ##Attachments attached to the course. E.g Timetable
    attachments = models.ManyToManyField(Attachment)
    
    def get_lectures(self):
        """
        Returns a list of all Lecture objects in this course.
        @return List Returns a list of Lecture objects.
        """
    
    
################################################################
#Testing/Marking Classes
################################################################

class Question(Base):
    """
    An instance of the Question class holds the question string
    with a List of answer objects that the user can pick.
    """
    ##The question text - Can be any format.
    content = models.TextField()
    ##The type of question - e.g Multiple Choice
    type = models.CharField(max_length=40)
    
    def get_answers(self):
        """
        Returns the possible answers for the question

CM2301/learn/views/announcement.py
from django.shortcuts import render
from learn.models import *
from learn.forms import *
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView


class CreateAnnouncementView(CreateView):
    model = Announcement
    template_name = "announcement_form.html"

    def form_valid(self, form):
        announcement = form.save(commit=False)
        announcement.owner = self.request.user
        announcement.save()
        return super(CreateAnnouncementView, self).form_valid(form)

CM2301/learn/views/course.py
from django.shortcuts import render, get_object_or_404
from learn.models import *
from django.contrib.auth.decorators import login_required
from django.http import Http404


@login_required
def course(request, course_id):
    values = dict()

    values['course'] = get_object_or_404(Course, pk=course_id)

    if values['course'] in request.user.course.all():
        values['modules'] = values['course'].modules.all()
        values['title'] = values['course'].title+" - Modules"
        return render(request, "modules_overview.html", values)
    else:
        raise Http404

CM2301/learn/templates/attachment.html
{% extends "base_navbar.html" %}

{% block content %}

<script src="{{ STATIC_URL }}js/jquery.dateFormat-1.0.js"></script>

<script>
	$(document).ready(function(){
		$('form#newRevision').submit(function(){
			var formData = new FormData($(this)[0]);
			$.ajax({
				url: 'add/',
				type: 'POST',
				data: formData,
				async: false,
				success: function (data) {
					try{
						$('#addRevisionModal').modal('hide');
						console.log(data)
						//appendTable(data)
						//$('html,body').scrollTop(0);
						setTimeout( function(){
							location.reload()
							}, 1200 );
						return false
					}
					catch(err){
						console.log(err.message)
						return false
					}
					
            		//$('#addRevisionModal').modal('hide');
        		},
        		cache: false,
				contentType: false,
        		processData: false
			})
			return false
		});
	});
	
	function appendTable(data){
		data = $.parseJSON(data)
		var version = data[0]['fields']['version']
		var time_uploaded = new Date(data[0]['fields']['time_uploaded'])
		var user = data[0]['fields']['uploaded_by']
		time_uploaded = $.format.date(time_uploaded.toString(), "d MMM yyyy, h:mm p")
		var file_size = Math.round((data[0]['fields']['file_size']/1024) * 10 ) / 10;
		file_size = file_size + ' KB'
		
		html = "<tr> <td>" + version + "</td> <td>" + time_uploaded + "</td> <td>" + file_size + "</td> <td><a href='/users/" + user  + "'>User</a></td> </tr>" + $('#revisionButtons').html
		
		//$(html).prependTo("#revisionTable > tbody");
		//$("#revisionTable tbody").prepend(html);
		$(html).insertAfter("#revisionTable tr:first");
	}
</script>


<h3>
	<a href="{{ attachment.get_latest_revision.get_absolute_url }}download">
		{{ attachment.file_name }}
	</a>
</h3>
<div class="row-fluid">
	<div class="span2">
		<img src="{{ STATIC_URL }}img/filetype/fileicon_bg.png" />
	</div>
	<div class="span10">
		<dl class="dl-horizontal">
			<dt>Filename</dt>
			<dd>{{ attachment.file_name }}</dd>
			<dt>Size</dt>
			<dd>{{ attachment.get_latest_revision.file_size|filesizeformat }}</dd>
			<dt>Total Size</dt>
			<dd>{{ attachment.get_total_size|filesizeformat }}</dd>
			<dt>Owner</dt>
			<dd>
				<a href="{{ attachment.owner.get_absolute_url }}">
					{{ attachment.owner }}
				</a>
			</dd>
		</dl>
	</div>
</div>

<h3>Revisions</h3>
<table class="table" id="revisionTable">
	<tr>
		<th>Version</th>
		<th>Time Uploaded</th>
		<th>File Size</th>
		<th>Uploaded By</th>
		<th></th>
	</tr>
	<tbody>
	{% for revision in attachment.revision_set.all %}
	<tr>
		<td>{{ revision.version }}</td>
		<td>{{ revision.time_uploaded }}</td>
		<td>{{ revision.file_size|filesizeformat }}</td>
		<td>
			<a href="/users/{{ revision.uploaded_by.id }}">
				{{ revision.uploaded_by }}
			</a>
		</td>
		<td id=#revisionButtons>
			<a class="btn btn-small" href="{{ revision.get_absolute_url }}download">
				<i class="icon-download-alt"></i>
			</a>
			<a class="btn btn-small" href="{{ revision.get_absolute_url }}delete">
				<i class="icon-remove"></i>
			</a>
		</td>
	</tr>
	{% endfor %}
	</tbody>
</table>
<a class="btn" href="#addRevisionModal" role="button" data-toggle="modal">
	Add Revision
	<i class="icon-plus">
	</i>
</a>
<a class="btn" href="{{ revision.attachment.get_absolute_url }}download">
	ZIP
	<i class="icon-download-alt">
	</i>
</a>

<div id="addRevisionModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="addRevisionModal" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3>Add revision</h3>
  </div>
  <div class="modal-body">
  	<p>
  		Add a new revision to {{ attachment.file_name }}
  	</p>
  	<form id="newRevision" enctype="multipart/form-data" method="post" action="">{% csrf_token %}
	<p>{{ form.attachment.as_hidden }}</p>
	<p>{{ form.uploaded_by.as_hidden }}</p>
  	<p>{{ form.file }}</p>
	<input type="submit" value="Submit" class="btn"/>
</form>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
</div>

{% endblock %}

CM2301/learn/templates/attachment_create.html
{% extends "base_navbar.html" %}

{% block content %}

<form enctype="multipart/form-data" method="post" action="">{% csrf_token %}
	<p>{{ attachment_form.object_id.as_hidden }}</p>
	<p>{{ attachment_form.file_name.label_tag }}{{ attachment_form.file_name }}</p>
	<p>{{ attachment_form.description.label_tag }}{{ attachment_form.description }}</p>
  	<p>{{ revision_form.file }}</p>
	<input type="submit" value="Submit" class="btn"/>
</form>
{% endblock %}

CM2301/learn/templates/base_navbar.html
{% extends "base.html" %}

{% block navbar %}
<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container-fluid">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </a>
			<a class="brand" href="/">LCARS</a>
			<div class="nav-collapse collapse">
				<p class="navbar-text pull-right">
                {% if user.is_authenticated %}
                Logged in as <a href="/logout/" class="navbar-link">{{ user.username }}</a>
                {% else %}
                    <a href="/login/">Log In</a>
                {% endif %}
				</p>
				<ul class="nav">
					<li> 
						<a href="/">Overview</a>
					</li>
					<li class="dropdown" id="menu1">
						<a class="dropdown-toggle" data-toggle="dropdown" href="#"> Modules <b class="caret"></b> </a>
						<ul class="dropdown-menu">
							<li>
								<a href="/modules/"><b>Module Overview</b></a>
							</li>
							<li class="divider"></li>
                            {% for module in modules %}
							<li>
								<a href="/modules/{{module.id}}"><b>{{ module.module_code }}</b> - <i>{{ module.title }}</i></a>
							</li>
                            {% endfor %}
						</ul>
					</li>
<!--					<li>
						<a href="/coursework">Coursework</a>
					</li>-->
					<li>
					
						<a href="/tests">Tests</a>
					</li>
<!--
					<li>
						<a href="/progress">Progress</a>
					</li>
                    -->
                    {% if user.is_staff %}
                    <li>
                        <a href="/management">Management</a>
                    </li>
                    <li>
                        <a href="/admin">Admin</a>
                    </li>
                    {% endif %}
               </ul>
			</div><!--/.nav-collapse -->
		</div>
	</div>
</div>

{% endblock %}

CM2301/learn/templates/management_courses.html
{% extends "base_navbar.html" %}

{% block content %}


<div class="row-fluid">
    <div class="well">
        <h2>LCARS - Course Management</h2>
        <div id="create-course-modal" class="modal hide fade">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h3>Create Course</h3>
            </div>
            <div class="modal-body">
                <p>One fine body…</p>
            </div>
            <div class="modal-footer">
            </div>
        </div>  
        <a href="/management/courses/create" class="btn btn-small" data-toggle="modal" data-target="#create-course-modal"><i class="icon-plus-sign"></i> New Course</a>
    </div>
    {% if course_list %}
    <!--Update user modal dialog-->
        <div id="update-course-modal" class="modal hide fade">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h3>Modify Course</h3>
            </div>
            <div class="modal-body">
                <p>One fine body…</p>
            </div>
            <div class="modal-footer">
            </div>
        </div>  
    <table class="table table-striped">
        <tr>
            <th>Course Title</th>
            <th>Course Code</th>
            <th>Course Description</th>
            <th>Edit</th>
        </tr>
        {% for course in course_list %}
        <tr>
            <td><a href="/management/courses/{{course.id}}/details">{{ course.title }}</td>
            <td>{{ course.code }}</td>
            <td>{{ course.description }}</td>
            <td><a data-toggle="modal" data-target="#update-course-modal" href="/management/courses/{{course.id}}/update"><i class="icon-edit"></i></a></td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}
</div>
{% endblock %}

CM2301/learn/templates/management_user_create.html
<form action="/management/users/create" method="POST">{% csrf_token %}
    {{form.as_p}}
   <input type="submit" class="btn" value="Submit" />
</form>

CM2301/learn/templates/management_users.html
{% extends "base_navbar.html" %}

{% block content %}


<div class="row-fluid">
    <div class="well">
        <h2>LCARS - User Management</h2>
        <div id="create-user-modal" class="modal hide fade">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h3>Create User</h3>
            </div>
            <div class="modal-body">
                <p>One fine body…</p>
            </div>
            <div class="modal-footer">
            </div>
        </div>  
        <a href="/management/users/create" class="btn btn-small" data-toggle="modal" data-target="#create-user-modal"><i class="icon-user"></i> New User</a>
    </div>
    {% if user_list %}
    <!--Update user modal dialog-->
        <div id="update-user-modal" class="modal hide fade">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h3>Update User</h3>
            </div>
            <div class="modal-body">
                <p>One fine body…</p>
            </div>
            <div class="modal-footer">
            </div>
        </div>  
    <table class="table table-striped">
        <tr>
            <th>Username</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email Address</th>
            <th>Phone Number</th>
            <th>Last Login</th>
            <th>Edit</th>
        </tr>
        {% for user in user_list %}
        <tr>
            <td>{{ user.username }}</td>
            <td>{{ user.first_name }}</td>
            <td>{{ user.last_name }}</td>
            <td>{{ user.email }}</td>
            <td>{{ user.phone }}</td>
            <td>{{ user.last_login }}</td>
            <td><a data-toggle="modal" data-target="#update-user-modal" href="/management/users/{{user.id}}/update"><i class="icon-edit"></i></a></td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}
</div>
{% endblock %}

CM2301/learn/templates/module_coursework_create.html
<form action="/modules/{{module_id}}/coursework/create" method="POST">{% csrf_token %}
    {{form.as_p}}
   <input type="submit" class="btn" value="Submit" />
</form>

CM2301/learn/templates/video_list.html
{% extends "base_navbar.html" %}

{% block content %}
<ul>
{% for video in videos %}
	<li>{{video.id}}</li>
{% endfor %}
</ul>
{% endblock %}